# Generated by Django 4.1.7 on 2024-10-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favourited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
